### ISSUE TITLE
Docker is updated to 8.3 which is not desirable

### ISSUE THREAD

**Issue by jwag59** [NaohiroTamura/cross-sms-aarch64.sh#7]
In the file Dockerfile.centos8 there is a sequence of commands as follows:
RUN sed -i -e s/enabled=0/enabled=1/g /etc/yum.repos.d/CentOS-PowerTools.repo && \
    dnf update -y && \
    dnf install -y epel-release openssh which file

But the line with dnf update -y && causes the container to be updated to CentOS 8.3 which is not want we want.
This line should be removed to ensure the container stays at CentOS 8.2
In fact with this command present the make base_os=centos8 fails since lmod-ohpc fails to find a correct version of the lua-filesystem package.
Please update the Dockerfile.centos8

**Comment by NaohiroTamura** [comment]
Hi @jwag59,

Thank you for the report.
The problem is confirmed, and fixed.

Error:
 Problem: package ohpc-base-2.0-47.1.ohpc.2.0.aarch64 requires lmod-ohpc, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides lua-filesystem needed by lmod-ohpc-8.2.10-15.1.ohpc.2.0.aarch64
  - nothing provides lua-posix needed by lmod-ohpc-8.2.10-15.1.ohpc.2.0.aarch64

Thanks.
